# Automatically add crops to the db through SQLAlchemy
# in run.py directory
# 				from utils.db.crop_db import *

def add_crops(crops):
	print('Importing db and Crop')
	from solarvibes import db
	from solarvibes.models import Crop
	print('Starting inserting crops to db')
	for crop in crops:
		crop_to_db = Crop(**crops[crop])
		db.session.add(crop_to_db)
	db.session.commit()
	print('Crops added to db! Done!')


crops = {
			'plum':
					{
					'image':'/static/images/crops/tomato.png',
					'_name':'plum',
					'_variety':'tomato',
				 	'_family':'fruit',
					'_yield':2800, # gr
					'_space_x':30, # cm
					'_space_y':30, # cm
					'_space_z':1.1, # m
					'_density':0.001111, # plants/cm2
					'_fruit_quantity':26,
					'_fruit_size':7.6, # cm
					'_fruit_weight':62, # gr
					'_water':1000, # ml/day
					'_nutrient':18, # mSiemens
					'_radiation':720, # min/day
					'_dtg':12, # day
					'_dtm':180, # day
					'_soil_ph_min':6, 		'_soil_ph_opt':6.5, 		'_soil_ph_max':6.8,			# pH
					'_soil_temp_min':15,	'_soil_temp_opt':23,		'_soil_temp_max':30, 		# C
					'_soil_humi_min':50,	'_soil_humi_opt':60,		'_soil_humi_max':75, 		# %RH
					'_soil_nutrient_min':2,	'_soil_nutrient_opt':16,	'_soil_nutrient_max':40,	# mSiemens
					'_air_temp_min':17,		'_air_temp_opt':25,			'_air_temp_max':28, 		# C
					'_air_humi_min':60,		'_air_humi_opt':63,			'_air_humi_max':70,			# %RH
					},
			'romaine':
					{
					'image':'/static/images/crops/lettuce.png',
					'_name':'romaine',
					'_variety':'lettuce',
				 	'_family':'leafy',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'arugula':
					{
					'image':'/static/images/crops/arugula.png',
					'_name':'arugula',
					'_variety':'herb',
				 	'_family':'leafy',
					'_yield':0.671,
					'_space_x':2.04,
					'_space_y':2.04,
					'_space_z':30,
					'_density':0.240292,
					'_fruit_quantity':1,
					'_fruit_size':25,
					'_fruit_weight':0.671,
					'_water':50,
					'_nutrient':0.5,
					'_radiation':600,
					'_dtg':6,
					'_dtm':47,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.3, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':18,		'_air_temp_max':26,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'radicchio':
					{
					'image':'/static/images/crops/radicchio.png',
					'_name':'radicchio',
					'_variety':'unknown',
				 	'_family':'leafy',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'bell pepper':
					{
					'image':'/static/images/crops/bell_pepper.png',
					'_name':'bell pepper',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'cabbage':
					{
					'image':'/static/images/crops/cabbage.png',
					'_name':'cabbage',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'coriander':
					{
					'image':'/static/images/crops/coriander.png',
					'_name':'coriander',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'basil':
					{
					'image':'/static/images/crops/basil.png',
					'_name':'basil',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'squash':
					{
					'image':'/static/images/crops/squash.png',
					'_name':'squash',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'chive':
					{
					'image':'/static/images/crops/chive.png',
					'_name':'chive',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'corn':
					{
					'image':'/static/images/crops/corn.png',
					'_name':'sweet corn',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'black beans':
					{
					'image':'/static/images/crops/black_beans.png',
					'_name':'black bean',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'strawberry':
					{
					'image':'/static/images/crops/strawberry.png',
					'_name':'strawberry',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'plum2':
					{
					'image':'/static/images/crops/tomato2.png',
					'_name':'plum2',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'rice':
					{
					'image':'/static/images/crops/rice.png',
					'_name':'rice',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'chilli':
					{
					'image':'/static/images/crops/chilli.png',
					'_name':'chilli',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'cottom':
					{
					'image':'/static/images/crops/cottom.png',
					'_name':'cottom',
					'_variety':'something',
				 	'_family':'something',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
		}


# TO ADD THESE CROP DATASETS RUN:
if __name__ == '__main__':
	add_crops(crops)
